import 'package:flutter_modular_app_template/domain/entities/example_detail/example_detail_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import '../../../mvvm/viewmodel_state.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'example_state.freezed.dart';

@freezed
class ExampleState extends ViewModelState with _$ExampleState {
  const factory ExampleState({
    List<ExampleDetailEntity>? restaurants,
    @Default(false) bool adBannerLoaded,
  }) = _ExampleState;
}