name: flutter_modular_app_template
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Layout
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.4
  flutter_svg: ^2.0.2
  diacritic: ^0.1.3
  mask_text_input_formatter: ^2.4.0
  flutter_animate: ^4.2.0+1
  unicons: ^3.0.0
  gap: ^3.0.1
  fl_chart: ^0.69.0

  # State Management
  flutter_bloc: ^8.1.1

  # Services
#  firebase_core: ^3.6.0
#  firebase_analytics: ^11.3.3
#  firebase_crashlytics: ^4.1.3
#  firebase_performance: ^0.10.0+8
  hive: ^2.2.3

  # Helpers
  shared_preferences: ^2.0.13
  intl: ^0.19.0
  mocktail: ^1.0.3
  url_launcher: ^6.1.5
  logger: ^2.3.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_modular: ^6.3.3
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  path: ^1.8.3
  basic_utils: ^5.5.0
  pointycastle: ^3.9.1
  crypto:

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: ^9.1.0
  http_mock_adapter: ^0.6.1

  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - config/
    - assets/images/
    - assets/icons/

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700