import 'package:flutter_modular_app_template/domain/entities/example_item/example_item_entity.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import '../../../mvvm/viewmodel_state.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'home_state.freezed.dart';

@freezed
class HomeState extends ViewModelState with _$HomeState {
  const factory HomeState({
    List<ExampleItemEntity>? restaurants,
    @Default(false) bool adBannerLoaded,
  }) = _HomeState;
}